# miniDBMS — top-level Makefile
#
# Builds the MiniDBMS executable and the pinned Hyrise SQL parser.
# No CMake or Curses required.
#
# == Usage ==
#   make              — incremental build (default target)
#   make clean        — remove generated project output
#   make compdb       — clean rebuild under Bear, writes root compile_commands.json
#
# == Output layout ==
#   build/
#     MiniDBMS          — the executable
#     libsqlparser.so   — Hyrise SQL parser shared library (copied)
#     libStorageEngine.a
#     libSQLInterpreter.a
#     obj/              — object files and generated dependency files (*.d)
#   compile_commands.json  — LSP compilation database (generated by `make compdb`)

CXX       := g++
CC        := gcc
AR        := ar

CXXFLAGS  := -std=c++17 -O2 -Wall -MMD -MP
CFLAGS    := -O2 -Wall -MMD -MP
INCLUDES  := -Iinclude -Ilibs/sql-parser/src -Ilibs/linenoise
LDFLAGS   := -Lbuild -Wl,-rpath,'$$ORIGIN'
LDLIBS    := -lsqlparser

PARSER_DIR    := libs/sql-parser
PARSER_LIB    := $(PARSER_DIR)/libsqlparser.so
BUILD_PARSER  := build/libsqlparser.so

# Parser compatibility: Bison-generated code on modern GCC needs <cstdint>
PARSER_CFLAGS := -std=c++17 -O3 -fPIC -include cstdint

# Explicit source lists — every .cpp file in the project is listed here
# so the build graph is clear and no future source is silently pulled
# into an unintended archive.
MAIN_SRCS     := src/main.cpp
STORAGE_SRCS  := src/Domains.cpp src/Files.cpp src/StorageEngine.cpp src/Tables.cpp
INTERP_SRCS   := src/SQLInterface.cpp src/SQLInterpreter.cpp
C_SRCS        := libs/linenoise/linenoise.c

MAIN_OBJS     := $(patsubst src/%.cpp,build/obj/%.o,$(MAIN_SRCS))
STORAGE_OBJS  := $(patsubst src/%.cpp,build/obj/%.o,$(STORAGE_SRCS))
INTERP_OBJS   := $(patsubst src/%.cpp,build/obj/%.o,$(INTERP_SRCS))
C_OBJS        := build/obj/linenoise.o

ALL_OBJS      := $(MAIN_OBJS) $(STORAGE_OBJS) $(INTERP_OBJS) $(C_OBJS)
DEPS          := $(ALL_OBJS:.o=.d)

# Archives group project objects; main.o and linenoise.o link directly.
# This mirrors the original CMake library layout and avoids pulling in
# unreferenced objects that contain undefined vtable references
# (the Table base class has declared virtual functions with no out-of-line
# definition in the current codebase).
LIB_STORAGE     := build/libStorageEngine.a
LIB_STORAGE_OBJ := $(STORAGE_OBJS)
LIB_INTERP      := build/libSQLInterpreter.a
LIB_INTERP_OBJ  := $(INTERP_OBJS)

TARGET := build/MiniDBMS

# ======================================================================
# Default target
# ======================================================================

all: $(TARGET)

# Executable: main.o and linenoise.o are linked directly; the static
# archives supply the remaining project code.  Archive groups let the
# linker search each archive repeatedly until no new symbols are resolved.
$(TARGET): $(MAIN_OBJS) $(C_OBJS) $(LIB_STORAGE) $(LIB_INTERP) $(BUILD_PARSER)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $(MAIN_OBJS) $(C_OBJS) \
	  -Wl,--start-group $(LIB_STORAGE) $(LIB_INTERP) -Wl,--end-group $(LDLIBS)

# ======================================================================
# Archives
# ======================================================================

$(LIB_STORAGE): $(LIB_STORAGE_OBJ)
	@mkdir -p $(@D)
	$(AR) rcs $@ $^

$(LIB_INTERP): $(LIB_INTERP_OBJ)
	@mkdir -p $(@D)
	$(AR) rcs $@ $^

# ======================================================================
# Parser library
# ======================================================================

$(PARSER_LIB):
	$(MAKE) -C $(PARSER_DIR) LIB_CFLAGS="$(PARSER_CFLAGS)"

$(BUILD_PARSER): $(PARSER_LIB)
	@mkdir -p $(@D)
	cp $< $@

# ======================================================================
# C++ compilation (project sources)
# ======================================================================

build/obj/%.o: src/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c -o $@ $<

# ======================================================================
# C compilation (linenoise)
# ======================================================================

build/obj/linenoise.o: libs/linenoise/linenoise.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $(INCLUDES) -c -o $@ $<

# ======================================================================
# Dependency file auto-inclusion
# ======================================================================

-include $(DEPS)

# ======================================================================
# Housekeeping
# ======================================================================

.PHONY: all clean compdb

clean:
	rm -rf build/obj build/MiniDBMS build/libStorageEngine.a \
	  build/libSQLInterpreter.a build/libsqlparser.so

# Rebuild from scratch under Bear so that compile_commands.json captures
# every compile command for clangd / LSP tooling.
compdb:
	rm -f compile_commands.json
	$(MAKE) clean
	bear -- $(MAKE)
